CREATE TABLE TB_USER (
	ID 			INT 			NOT NULL AUTO_INCREMENT,
	USERNAME 	VARCHAR(50) 	NOT NULL,
	PASSWORD 	VARCHAR(100) 	NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE INDEX USERNAME_UK (USERNAME)
);

CREATE TABLE TB_POLL (
	ID 						INT 			NOT NULL AUTO_INCREMENT,
	TITLE 					VARCHAR(50) 	NOT NULL,
	DESCRIPTION 			VARCHAR(100),
    REQUIRE_AUTHENTICATION	INT 			NOT NULL DEFAULT 0,
	USER_ID 				INT 			NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE INDEX TITLE_UK (TITLE),
	CONSTRAINT ID_USER_FK FOREIGN KEY (USER_ID) REFERENCES TB_USER (ID)
);

CREATE TABLE TB_POLL_OPTION (
	ID			INT				NOT NULL AUTO_INCREMENT,
	DESCRIPTION	VARCHAR(50)		NOT NULL,
	POLL_ID		INT				NOT NULL,
    TOTAL_VOTES INT				NOT NULL DEFAULT 0,
	PRIMARY KEY (ID),
	UNIQUE INDEX DESC_POLL_UK (DESCRIPTION, POLL_ID),
	CONSTRAINT POOL_ID_FK FOREIGN KEY (POLL_ID) REFERENCES TB_POLL (ID)
);

CREATE TABLE TB_POLL_USER (
	ID 			INT 			NOT NULL AUTO_INCREMENT,
	POLL_ID		INT				NOT NULL,
	USER_ID		INT				NOT NULL,
	POLL_OPTION_ID 	INT,
	PRIMARY KEY (ID),
	UNIQUE INDEX POLL_USER_UK (POLL_ID, USER_ID),
	CONSTRAINT POOL_USER_POLL_ID_FK FOREIGN KEY (POLL_ID) REFERENCES TB_POLL (ID),
	CONSTRAINT POOL_USER_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES TB_USER (ID),
	CONSTRAINT POOL_USER_POLL_OPTION_ID_FK FOREIGN KEY (POLL_OPTION_ID) REFERENCES TB_POLL_OPTION (ID)
);
